# Generated by Django 3.1.14 on 2024-11-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20241122_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='desciption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
